baseURL = "https://Takou07.github.io/Boris-Blog/"
title = "Boris'BLog"
theme = "PaperMod"
languageCode = "fr-fr"

[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple_touch_icon.png"
  
[params]
    ShowReadingTime = true
    disableShare =  false
    defaultTheme = "auto" # ou "dark" pour le mode sombre par dÃ©faut
    [params.profileMode]
        enabled = false
    [params.homeInfoParams]
    title = "ðŸ‘‹ Bienvenue dans B'BLog" # Le gros titre
    content = """
    Data & AI Student | Boris TAKOU KENNE

    Bonjour, c'est Boris. Je documente mes notes d'apprentissage...
    Vu le nombre de fautes de frappe, vous devinerez que c'est bien moi qui Ã©cris 
    et non ChatGPTðŸ˜‰.    
    """
        # Les icÃ´nes sociaux (comme sur la capture)
        [[params.socialIcons]]
            name = "github"
            url = "https://github.com/Takou07"
        [[params.socialIcons]]
            name = "linkedin"
            url = "https://www.linkedin.com/in/boris-takou-kenne-948895253/"
        [[params.socialIcons]]
            name = "x" # ou "x" si vous prÃ©fÃ©rez le nouveau logo
            url = "https://x.com/boris_takou"
        [[params.socialIcons]]
            name = "email"
            url = "mailto:takouboris79@gmail.com"
        [[params.socialIcons]]
            name = "credly"
            url = "https://www.credly.com/users/boris-takou"  # Mettez votre vrai lien ici

# --- LE MENU (En haut Ã  droite) ---

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives"
    weight = 20

[[menu.main]]
    identifier = "projets"
    name = "Projets" # C'est votre nouvel onglet !
    url = "/projets"
    weight = 30

[[menu.main]]
    identifier = "recherche"
    name = "Rechercher"
    url = "/search"
    weight = 40

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 50

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 60
    
# Ajoutez ceci Ã  la racine de votre fichier hugo.toml (pas dans [params])
[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    category = "categories"
    tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true